MovieRecommedationWeb/urls.py
from django.contrib import admin
from django.urls import path, include

from userWeb import views

urlpatterns = [

    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('userWeb/', include("userWeb.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    # path('recommendation/', include("recommendation.urls")),
    # path('modelTraining/', include("modelTraining.urls")),

]

userWeb/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from userWeb import views as userWeb_views

app_name = "userWeb"
urlpatterns = [
    path('index/', userWeb_views.IndexView.as_view(), name="index"),
    path('admin/', userWeb_views.admin, name='admin'),
    path('movie/', userWeb_views.MovieView.as_view(), name="movie"),
    path('profile/<int:pk>/', userWeb_views.UserProfileView.as_view(), name='profile-detail'),
    # 继承自模板
    path('register/', userWeb_views.register_request, name='register'),
    # path('logout/', userWeb_views.MyLogoutView.as_view(), name='logout'),
    path('logout/',
         auth_views.LogoutView.as_view(next_page='userWeb:index',
                                       extra_context={'success_message': '注销成功！'}),
         name='logout'),
    path('login/',
         auth_views.LoginView.as_view(success_url='userWeb:index', template_name='userWeb/registration/login.html',
                                      redirect_authenticated_user=True),
         name='login'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/', userWeb_views.MyPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

userWeb/models.py
"""
存放models
用于设定对象的属性和操作
"""

# Create your models here.

from django.contrib.auth.models import User
from django.db import models


class Movie(models.Model):
    movie_id = models.IntegerField(unique=True)
    name = models.TextField()
    alias = models.TextField(null=True)
    actors = models.TextField(null=True)
    cover = models.TextField(null=True)
    directors = models.TextField(null=True)
    douban_score = models.FloatField(null=True)
    douban_votes = models.IntegerField(null=True)
    imdb_id = models.TextField(null=True)
    languages = models.TextField(null=True)
    mins = models.IntegerField(null=True)
    official_site = models.TextField(null=True)
    regions = models.TextField(null=True)
    release_date = models.TextField(null=True)
    storyline = models.TextField(null=True)
    genres = models.CharField(max_length=100, null=True)

    def __str__(self):
        if self.release_date and self.directors and self.genres:
            return f'{self.name}------导演：{self.directors}, 上映日期：{self.release_date}, 类型：{self.genres}'

        else:
            return self.name

    class Meta:
        '''
        Meta 类是用于定义模型的元数据。元数据是关于模型的一些附加信息，如排序方式、数据库表名称等。这些信息不是模型中的字段或方法，而是与模型本身相关的配置选项。
        '''
        ordering = ['-douban_votes', '-douban_score']


class Profile(models.Model):
    '''
    用户的其他资料，与基础模型user一对一关联
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_movies = models.ManyToManyField(Movie, related_name="users_who_like", blank=True)
    # 由于genres没有独立的模型，所以存储电影电影
    is_first_login = models.BooleanField(default=True)  # 标志用户是否为第一次登陆

    def __str__(self):
        res = f'{self.user.username} ------ 账户创建时间： {self.user.date_joined}'
        if self.is_first_login:
            return res + f', 是否为新用户： {self.is_first_login}'

        else:
            return res

userWeb/views.py
# todo 引入自带的contribAPP做用户登录登出等操作


from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.db import transaction
from django.forms import model_to_dict
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic

from MovieRecommedationWeb import forms as my_forms
from MovieRecommedationWeb.forms import RegistrationForm
from userWeb.models import Profile


# Create your views here.
class IndexView(generic.ListView):
    template_name = "userWeb/movies/home.html"
    # 记得要把APP添加到settings.py的的INSTALLED_APPS中不然系统不知道这个app，就不会在这里找templates
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        # return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        #        :5
        #        ]
        return


class MovieView(generic.ListView):
    template_name = "userWeb/movies/home.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """

        return


class UserProfileView(generic.DetailView):
    model = User
    template_name = "userWeb/users/profile.html"
    context_object_name = "user"

    def get(self, request, *args, **kwargs):
        user = self.get_object()  # 获取User对象
        user_values = model_to_dict(user)
        print(user_values)
        # profile = Profile.objects.get(user=user)  # 获取关联的Profile对象
        #
        # print(profile)
        exclude_fields = ['password', 'last_login', 'is_superuser', 'groups', 'user_permissions']
        filtered_user_values = {key: value for key, value in user_values.items() if key not in exclude_fields}

        context = {
            "user": user,
            "filtered_user_values": filtered_user_values,
            # "profile": profile,
        }
        return render(request, self.template_name, context)


class MyPasswordResetView(PasswordResetView):
    template_name = 'userWeb/registration/password_reset.html'
    success_url = 'userWeb:login'
    form_class = my_forms.MyPasswordResetForm

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user_name = form.cleaned_data['user_name']

        try:
            user = get_object_or_404(User, email=email, username=user_name)
            self.request.session['reset_password'] = True
            messages.success(self.request, "修改成功！")
            return redirect('userWeb:login')  # 跳转到重置密码页面
        except Http404:
            messages.error(self.request, '用户不存在，请重新输入。')
            return redirect('userWeb:password_reset')  # 用户不存在时，重定向回到表单页面并显示错误消息


def admin(request):
    return None

    # class RegisterView(generic.FormView):
    #     template_name = 'userWeb/registration/register.html'
    #     form_class = forms.RegistrationForm
    #     success_url = 'userWeb:index'
    #
    #     def form_valid(self, form):
    #         user = form.save()
    #         login(self.request, user)
    #         return super().form_valid(form)
    #
    #     def form_invalid(self, form):
    #         return redirect('userWeb:login')  # 跳转到login页面


def register_request(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():  # 保证数据库操作的原子性
                    user = form.save()
                    user_profile = Profile.objects.create(user=user, is_first_login=1)
                    login(request, user)
                    messages.success(request, "注册成功！")
                    return redirect("userWeb:index")
            except Exception as e:
                messages.error(request, str(e))

    else:
        form = RegistrationForm()

    context = {"register_form": form}

    if form.errors:
        context["error_form"] = form
        messages.error(request, "注册失败！")

    return render(request=request, template_name="userWeb/registration/register.html", context=context)

templates/userWeb/movies/base.html
{% load static %}
<!doctype html>
<html lang="zh">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="referrer" content="no-referrer">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'userWeb/movies/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'userWeb/movies/main.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<header class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light container">
        <a href="{% url 'userWeb:index' %}" class="navbar-brand">基于协同过滤的电影推荐网站</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav ml-auto">

                <!-- 其他导航项 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userWeb:index' %}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userWeb:movie' %}">电影</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userWeb:profile-detail' pk=user.pk %}">个人主页</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'userWeb:logout' %}" class="nav-link">注销</a>
                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a href="{% url 'admin:index' %}" class="nav-link">管理员入口</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'userWeb:login' %}" class="nav-link">登录</a>
                    </li>
                {% endif %}

            </ul>
            <form class="form-inline" action="" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="电影名称" aria-label="电影名称"
                           aria-describedby="basic-addon2" name="movieName">
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit">搜索</button>
                    </div>
                </div>
            </form>
        </div>
    </nav>
</header>

<main class="container">
    {% if messages %}
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% block content %}{% endblock %}
    {#    <div class="row mt-4">#}
    {#        <div class="col-md-9">#}
    {#            {% block content %}{% endblock %}#}
    {#        </div>#}
    {#        <div class="col-md-3">#}
    {#            <!-- 侧边栏内容 -->#}
    {#            <a>test</a>#}
    {#        </div>#}
    {#    </div>#}
</main>

<footer class="bg-light mt-4 py-3">
    <div class="container text-center">
        <!-- 页脚内容 -->
    </div>
</footer>

<script src="{% static 'userWeb/movies/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'userWeb/movies/popper.min.js' %}"></script>
<script src="{% static 'userWeb/movies/bootstrap.min.js' %}"></script>
{% block JavaScript %}{% endblock %}
</body>

</html>

templates/userWeb/movies/friends.html
{% extends 'userWeb/movies/base.html' %}

{% block content %}
<style>
    .user-card {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 1rem;
        padding: 1rem;
    }

    .user-card button {
        outline: none;
        border: none;
        padding: .5rem;
        border-radius: 5px;
    }

    #userCard button:hover {
        background-color: purple;
        color: #ffffff;
    }

    #friendCard button:hover {
        background-color: red;
        color: #fff;
    }

    .user-avatar {
        height: 180px;
        width: 180px;
        border-radius: 50%;
    }

    .friend-wrapper {
        min-height: 500px;
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        justify-content: center;
        align-items: center;
    }

    .user-avatar {
        transition: .5s;
    }

    .user-avatar:hover {
        transform: scale(1.1);
    }
</style>

<div style="height: 10px;"></div>

<div>

    {% if with_friends %}
    <h2>好友列表:</h2>
    <div class="friend-wrapper">
        {% for friend in friends %}
        <div class="user-card" id="friendCard">
            <img src="{{ friend.profile.image.url }}" class="user-avatar">
            <h4>{{ friend.username }}</h4>
            <button data-userid="{{ friend.id}}" data-curruser="{{ user.id }}"
                data-url="{% url 'remove-friend' %}">删除好友</button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h2>您还没有任何好友哦，可以添加下面的好友</h2>
    {% endif %}

    <h2>向您推荐的好友:</h2>
    <div class="friend-wrapper">
        {% for otheruser in rec_friends %}
        <div class="user-card" id="userCard">
            <a href="/movies/others_liked_moives?user_id={{otheruser.id}}">
                <img src="{{ otheruser.profile.image.url }}" class="user-avatar">
            </a>
            <h4>{{ otheruser.username }}</h4>
            <button data-userid="{{otheruser.id}}" data-curruser="{{ user.id }}"
                data-url="{% url 'add-friend' %}">添加好友</button>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block JavaScript %}
<script>
    $(document).ready(function () {
        $('#friendCard button').click(function () {
            var oThis = $(this);
            var userId = oThis.attr('data-userid');
            var url = oThis.attr('data-url');
            var curr_user = oThis.attr('data-curruser');

            $.ajax(
                {
                    type: 'GET',
                    url: url,
                    data: {
                        'user_id': userId,
                        'curr_user': curr_user,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.status === 'success') {
                            alert('删除成功');
                        }
                    }
                }
            )
        });
        $('#userCard button').click(function () {
            var oThis = $(this);
            var userId = oThis.attr('data-userid');
            var url = oThis.attr('data-url');
            var curr_user = oThis.attr('data-curruser');

            $.ajax(
                {
                    type: 'GET',
                    url: url,
                    data: {
                        'user_id': userId,
                        'curr_user': curr_user,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.status === 'success') {
                            alert('添加成功');
                        }
                    }
                }
            )
        });
    })
</script>
{% endblock %}

templates/userWeb/movies/home.html
{% extends 'userWeb/movies/base.html' %}
{% block content %}
    {% load static %}

    <div class="row text-center bg-light">


        {% for movie in movie_list %}

            <div class="col">
                <figure class="figure mt-4">
                    <img class="rounded-lg float-left shadow border border-white" src="{{ movie.cover }}"
                         alt="{{ movie.name }}--图像失效" style="height: 420px; width: 300px;">

                    <figcaption class="figure-caption text-center">
                        <a href="/movies/{{ movie.id }}" style="font-size:20px; text-decoration: none;">
                            {{ movie.name }}
                        </a>
                        <span style="color:red; font-size:20px;">
                    {{ movie.douban_score }}
                </span>

                        {% if user.is_authenticated and movie in user.moviepreference.favorite_movie.all %}
                            <button data-href="{% url 'movies-toggle-like' %}" data-movieId="{{ movie.id }}"
                                    data-userName="{{ user.username }}" class="btn btn-like btn-outline-danger">移除‘喜欢’
                            </button>
                        {% elif user.is_authenticated %}
                            <button data-href="{% url 'movies-toggle-like' %}" data-movieId="{{ movie.id }}"
                                    data-userName="{{ user.username }}" class="btn btn-like btn-outline-info">喜欢
                            </button>
                        {% endif %}

                    </figcaption>
                </figure>
            </div>


        {% endfor %}

    </div>

    <div class="row bg-light" style="height: 20px;"></div>

    <div class="row bg-light">
        <div class="col-12 text-center">

            {% if is_paginated %}

                {% if page_obj.has_previous %}
                    <a href="?page=1" class="btn  btn-outline-info mb-4">First</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a href="?page={{ num }}" class="btn btn-info mb-4">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
                        <a href="?page={{ num }}" class="btn btn-outline-info mb-4">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
                {% endif %}

            {% endif %}
        </div>


    </div>




{% endblock %}

{% block JavaScript %}
    <script type="text/javascript">
        $(document).ready(function () {

            $('.btn-like').click(function () {
                var oThis = $(this);
                var nMovieId = oThis.attr('data-movieId');
                var sUserName = oThis.attr('data-userName');
                var sUrl = oThis.attr('data-href');

                $.ajax({
                    type: "GET",
                    url: sUrl,
                    data: {
                        "movie_id": nMovieId,
                        "username": sUserName,
                    },
                    dataType: "json",

                    success: function (data) {
                        // alert(data.status);
                        if (data.status == 'liked') {
                            oThis.removeClass('btn-outline-info').addClass('btn-outline-danger').html('移除‘喜欢’');
                        } else if (data.status == 'disliked') {
                            oThis.removeClass('btn-outline-danger').addClass('btn-outline-info').html('喜欢');
                        }
                    }
                });
            });


            $('.figure').hover(
                function () {

                    $(this).find('img').addClass('rounded-sm shadow-lg').addClass('');
                },
                function () {
                    $(this).find('img').removeClass('rounded-sm shadow-lg').removeClass('btn-infol');
                }
            )

        });

    </script>
{% endblock %}

templates/userWeb/movies/liked_movies.html
{% extends 'userWeb/movies/base.html' %}
{% block content %}

<div class="container-fluid" style="text-align: left;">
    <div class="row row-cols-1" style="height: 30px;">

    </div>

    <div class="row ">


        {% for movie in user.moviepreference.favorite_movie.all %}
        <div class="col">

            <figure class="figure">
                <img class="rounded-lg float-left shadow-lg border border-white" src="{{ movie.cover }}"
                    alt="{{ movie.cover }}" style="height: 420px; width: 300px;">

                <figcaption class="figure-caption text-center">
                    <a href="/movies/{{movie.id}}" style="font-size:18px; text-decoration: none;">
                        {{ movie.name}}
                    </a>
                    <span style="color:red; font-size:18px;">
                        {{movie.douban_score}}
                    </span>

                </figcaption>
            </figure>


        </div>

        {% endfor %}

        </ul>
    </div>




</div>
</div>
{% endblock %}

templates/userWeb/movies/movie_detail.html
{% extends 'userWeb/movies/base.html' %}
{% block content %}


<div class="container-fluid" style="text-align: center;">
    <div class="row row-cols-1" style="height: 30px;">

    </div>

    <div class="row row-cols-4">


        <div class="col">

            <figure class="figure">
                <img class="rounded-lg float-left shadow-lg border border-white" src="{{ object.cover }}"
                    alt="{{ object.cover }}" style="height: 840px; max-width: 600px;">
                <figcaption class="figure-caption">


                    <h1 style="color: black;font: outline;">
                        {{object.name}}
                    </h1><br>

                    {% if object.alias %}
                    <p style="font-size: large; color:black">
                        别名: {{object.alias}}
                    </p>
                    {% endif %}

                    {% if object.directors %}
                    <a style="font-size: 30px; text-decoration: none;" href="#">
                        导演: {{object.directors}}
                    </a><br>
                    {% endif %}

                    <div style="height: 30px;"></div>

                    {% if object.actors %}
                    <h5 style="text-align: justify;">
                        主演: {{object.actors}}
                    </h5><br>
                    {% endif %}

                    {% if object.regions %}
                    <h5 style="color:black;">
                        地区： {{object.regions}}
                    </h5><br>
                    {% endif %}

                    {% if object.languages %}
                    <h5>
                        语言： {{object.languages}}
                    </h5>
                    {% endif %}

                    <div style="height: 30px;"></div>

                    {% if object.release_date %}
                    <h5 style="color: dodgerblue;">
                        上映日期： {{object.release_date}}
                    </h5><br>
                    {% endif %}

                    {% if object.storyline %}
                    <p style="font-size: large; font-weight: 200; color:black; text-align: justify;">
                        故事梗概： {{object.storyline}}
                    </p>
                    {% endif %}

                    {% if object.douban_votes %}
                    <p style="font-size: 20px; color:red">
                        人气： {{object.douban_votes}}
                    </p>
                    {% endif %}

                    <p>
                        <a href="https://www.baidu.com/s?wd={{object.name}}+豆瓣" class="btn btn-info"
                            target="_blank">在互联网上搜索详情</a>

                        {% if user.is_authenticated and object in user.moviepreference.favorite_movie.all %}
                        <button data-href="{% url 'movies-toggle-like' %}" data-movieId="{{ object.id }}"
                            data-userName="{{ user.username }}" class="btn btn-like btn-outline-danger">移除‘喜欢’</button>
                        {% elif user.is_authenticated %}
                        <button data-href="{% url 'movies-toggle-like' %}" data-movieId="{{ object.id }}"
                            data-userName="{{ user.username }}" class="btn btn-like btn-outline-info">喜欢</button>
                        {% endif  %}


                    </p>
                </figcaption>
            </figure>
        </div>
        </ul>
    </div>

</div>
</div>
{% endblock %}

{% block JavaScript%}
<script type="text/javascript">
    $(document).ready(function () {

        $('.btn-like').click(function () {
            var oThis = $(this);
            var nMovieId = oThis.attr('data-movieId');
            var sUserName = oThis.attr('data-userName');
            var sUrl = oThis.attr('data-href');

            $.ajax({
                type: "GET",
                url: sUrl,
                data: {
                    "movie_id": nMovieId,
                    "username": sUserName,
                },
                dataType: "json",

                success: function (data) {
                    // alert(data.status);
                    if (data.status == 'liked') {
                        oThis.removeClass('btn-outline-info').addClass('btn-outline-danger').html('移除‘喜欢’');
                    }
                    else if (data.status == 'disliked') {
                        oThis.removeClass('btn-outline-danger').addClass('btn-outline-info').html('喜欢');
                    }
                }
            });
        });
    });
</script>
{% endblock %}

templates/userWeb/movies/movie_rec.html
{% extends 'userWeb/movies/base.html' %}
{% block content %}

<div class="container-fluid" style="text-align: center;">

    {% if is_random %}
    <div class="alert-info" style=" font-size: larger;">您现在没有收藏任何电影，因此本次的推荐是随机的</div>
    {% endif %}

    <div class="row row-cols-4">


        {% for movie in movie_list%}
        <div class="col">

            <figure class="figure">
                <img class="rounded-lg float-left shadow-lg border border-white" src="{{ movie.cover }}"
                    alt="{{ movie.cover }}" style="height: 420px; width: 300px;">

                <figcaption class="figure-caption text-center">
                    <a href="/movies/{{movie.id}}" style="font-size:18px; text-decoration: none;">
                        {{ movie.name}}
                    </a>
                    <span style="color:red; font-size:18px;">
                        {{movie.douban_score}}
                    </span>

                </figcaption>
            </figure>


        </div>

        {% endfor %}

    </div>




</div>
</div>
{% endblock %}

templates/userWeb/movies/others_liked_movies.html
{% extends 'userWeb/movies/base.html' %}
{% block content %}

<div class="container-fluid" style="text-align: left;">
    <div class="row row-cols-1" style="height: 30px;">

    </div>

    <h1>{{ username }} 喜欢的电影:</h1>
    <div class="row ">


        {% for movie in movie_list %}
        <div class="col">

            <figure class="figure">
                <img class="rounded-lg float-left shadow-lg border border-white" src="{{ movie.cover }}"
                    alt="{{ movie.cover }}" style="height: 420px; width: 300px;">

                <figcaption class="figure-caption text-center">
                    <a href="/movies/{{movie.id}}" style="font-size:18px; text-decoration: none;">
                        {{ movie.name}}
                    </a>
                    <span style="color:red; font-size:18px;">
                        {{movie.douban_score}}
                    </span>

                </figcaption>
            </figure>

        </div>

        {% endfor %}

        </ul>
    </div>




</div>
</div>
{% endblock %}